### ISSUE TITLE
scribe inserting not white-listed tags

### ISSUE THREAD

**Issue by jackmoore** [guardian/scribe-plugin-sanitizer#19]
Even though I did not put `p` or `br` tags on my whitelist, scribe is still inserting them.  Is there a way to prevent this?

**Comment by rrees** [comment]
Could you supply a bit more information? Ideally an example would be great.

The `br` and `em` tag is automatically whitelisted (without override) because Scribe needs them to implement things like markers, the editor won't work without them.

The `p` tag I suspect might be due to the browser's contenteditable behaviour.
